# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

executors:
  maven-executor:
    docker:
      - image: cimg/openjdk:21.0
    working_directory: ~/spring5-recipe-app

jobs:
  build-and-test:
    executor: maven-executor
    environment:
      MAVEN_OPTS: -Xmx3200m
    steps:
      - checkout

      # Restore Maven dependencies cache
      - restore_cache:
          keys:
            - maven-{{ checksum "pom.xml" }}
            - maven-

      # Install dependencies offline
      - run:
          name: Install dependencies
          command: mvn install -DskipTests

      # Save Maven cache
      - save_cache:
          paths:
            - ~/.m2
          key: maven-{{ checksum "pom.xml" }}

      # Run all tests (unit + integration) and generate JaCoCo coverage
      - run:
          name: Run Tests with JaCoCo
          command: mvn verify jacoco:report

      # Save JaCoCo HTML reports as artifacts
      - store_artifacts:
          path: target/site/jacoco
          destination: coverage-report

      # Upload to Codecov
      - run:
          name: Upload Coverage to Codecov
          command: bash <(curl -s https://codecov.io/bash)

workflows:
  build-and-test:
    jobs:
      - build-and-test